In [14]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import *
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [2]:
dataset=pd.read_csv('C:/Users/psing/Box/LetsUpgrade AI-ML/Day 25/train.csv')

In [5]:
dataset.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

# Lable encoder for string to numberical

In [6]:
le=preprocessing.LabelEncoder()

In [8]:
dataset['Sex']=le.fit_transform(dataset['Sex'])

In [9]:
dataset['Embarked']=le.fit_transform(dataset['Embarked'])

In [10]:
dataset1=dataset.drop(['PassengerId', 'Cabin', 'Ticket', 'Name'], axis = 1)

In [11]:
dataset1.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [12]:
print (dataset1.columns.to_list())

['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']


# define a custom fuction

In [39]:
def custom_fn(a):
    dataset_cust=dataset1.columns.to_list()
    dataset_cust.remove(a)
    
    print('Independent Variales : ',*dataset_cust,'\n')
    print('Dependent Variales : ',a,'\n')
    
    y=dataset1[a]
    X=dataset1.drop([a],axis=1)
    
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
    
    clf=BernoulliNB()
    
    y_pred=clf.fit(X_train,y_train).predict(X_test)
    
    acc=accuracy_score(y_test,y_pred,normalize=True)*100
    
    print('Accuracy Score in percentage (%) is ',acc,'\n')
    print('\n Confusion matrix is as following: \n',confusion_matrix(y_test, y_pred))

# Passenger Class as dependent variable

In [40]:
custom_fn('Pclass')

Independent Variales :  Survived Sex Age SibSp Parch Fare Embarked 

Dependent Variales :  Pclass 

Accuracy Score in percentage (%) is  59.176029962546814 


 Confusion matrix is as following: 
 [[ 30   8  32]
 [  9  10  30]
 [ 24   6 118]]


# Gender as dependent variable

In [41]:
custom_fn('Sex')

Independent Variales :  Survived Pclass Age SibSp Parch Fare Embarked 

Dependent Variales :  Sex 

Accuracy Score in percentage (%) is  74.53183520599251 


 Confusion matrix is as following: 
 [[ 49  49]
 [ 19 150]]


# SibSP as dependent variable

In [42]:
custom_fn('SibSp')

Independent Variales :  Survived Pclass Sex Age Parch Fare Embarked 

Dependent Variales :  SibSp 

Accuracy Score in percentage (%) is  68.91385767790263 


 Confusion matrix is as following: 
 [[162  20   0   0   0   0   0]
 [ 43  22   0   0   0   0   0]
 [  6   2   0   0   0   0   0]
 [  5   2   0   0   0   0   0]
 [  2   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0]]


# Parch as dependent variable

In [43]:
custom_fn('Parch')

Independent Variales :  Survived Pclass Sex Age SibSp Fare Embarked 

Dependent Variales :  Parch 

Accuracy Score in percentage (%) is  71.53558052434457 


 Confusion matrix is as following: 
 [[182  16   0   0   0]
 [ 31   9   0   0   0]
 [ 24   3   0   0   0]
 [  1   0   0   0   0]
 [  1   0   0   0   0]]


# Embarked as dependent variable

In [44]:
custom_fn('Embarked')

Independent Variales :  Survived Pclass Sex Age SibSp Parch Fare 

Dependent Variales :  Embarked 

Accuracy Score in percentage (%) is  73.40823970037454 


 Confusion matrix is as following: 
 [[  0   0  49]
 [  0   0  22]
 [  0   0 196]]
