# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.32200186 0.65966763 0.00717997]
  [0.36387151 0.32955556 0.39002235]
  [0.21909399 0.96383568 0.3425688 ]]

 [[0.58308852 0.07595936 0.24691828]
  [0.89796522 0.05986538 0.38391593]
  [0.72135335 0.87685534 0.87177217]]

 [[0.5796398  0.35303799 0.43033588]
  [0.3084238  0.19993782 0.36479586]
  [0.69575563 0.4502276  0.46745925]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [7]:
np.diag([1,2,3,4],-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [8]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [17]:
import numpy as np
x= np.random.random((3,3))
print("Original Array:")
print(x)

xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)


Original Array:
[[0.39297799 0.49119902 0.82817235]
 [0.21372007 0.07660802 0.00322309]
 [0.70778411 0.50434155 0.8364806 ]]
After normalization:
[[0.46774844 0.58562441 0.99002919]
 [0.25261937 0.08806993 0.        ]
 [0.84555015 0.60139688 1.        ]]


# 5.  How to find common values between two arrays?

In [20]:
arr1 = np.array([1,2,3,4,5])
print("1st Array: ",arr1)

arr2 = [1,3,5]
print("2nd Array2: ",arr2)

print("Common values between 1st and 2nd :")

print(np.intersect1d(arr1, arr2))

1st Array:  [1 2 3 4 5]
2nd Array2:  [1, 3, 5]
Common values between 1st and 2nd :
[1 3 5]


# 6.How to get the dates of yesterday, today and tomorrow?

In [21]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [30]:
x, y = np.random.randint(0,2,6), np.random.randint(0,2,6)
print("First array:",x)
print("Second array:",y)
array_equal = np.allclose(x, y)
print("Test above two arrays are equal ? = ",array_equal )

First array: [0 1 1 1 0 0]
Second array: [1 0 1 0 0 1]
Test above two arrays are equal ? =  False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [41]:
x = np.random.randint(10,100, size=10);
print("Original array:")
print(x)
y= x[x.argmax()]
print("Maximum value is ",y)

x[x.argmax()] = 0
print("Maximum value replaced by 0")
print(x)


Original array:
[81 37 53 55 19 27 83 70 62 63]
Maximum value is  83
Maximum value replaced by 0
[81 37 53 55 19 27  0 70 62 63]


# 9. How to print all the values of an array?

In [44]:
y=np.arange(50)
print(y)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


# 10.Subtract the mean of each row of a matrix

In [56]:
print("Matrix:\n")
X = np.arange(15).reshape(5,3)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Matrix:

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Subtract the mean of each row of the said matrix:

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

Sorry couldn't understand question

# 12.How to get the diagonal of a dot product?

In [62]:
a = [[1,2],[6,5]]
b = [[1,2],[6,5]]

np.diagonal(np.dot(a,b))


array([13, 37])

# 13.How to find the most frequent value in an array?

In [64]:
x = np.random.randint(0, 100, 40)
print(x)
print("Most frequent value :")
print(np.bincount(x).argmax())

[46 98 15 67 88 85 96 65 78  5 97 31 24 17 68 69 73 15 42 65  1 99 94  4
 61 29 14  7 98 80  2 38 72  6 43 27 81 44 63 15]
Most frequent value :
15


# 14.How to get the n largest values of an array

In [76]:
x = np.random.randint(0, 100, 40)
print(x)
print("Largest Value:")
print (x[np.argsort(x)[-1:]])

[39 39  0 99 73 50 24 67 25 60 87 78 58 18 45 86 21 40 76 65 30 22 42 28
 85 12  3 79 30 75 41 74 63 33 40 58 59 61 11 37]
Largest Value:
[99]


# 15.How to create a record array from a regular array?

In [77]:
a1=np.array([1,2,3,4])
a2=np.array(['Delhi','Mumbai','Chennai','Kolkata'])
result= np.core.records.fromarrays([a1, a2])
print(result[0])
print(result[1])
print(result[2])

(1, 'Delhi')
(2, 'Mumbai')
(3, 'Chennai')
